version: 2
updates:
  - packages-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: 10:17
  - packages-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: 10:17
  - packages-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: 10:17