name: "analyse semgrep"
on: 
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.1.0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout
      - run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep.sarif
